#!/bin/bash

# Local PostgreSQL Database Setup

DB_NAME="tvproje"
DB_USER="postgres"
DB_PASSWORD="333333"
ADMIN_EMAIL="orhanozan33@hotmail.com"
ADMIN_PASSWORD="33333333"

echo "🚀 Setting up local PostgreSQL database..."

# Check if PostgreSQL is running
if ! pg_isready -q; then
    echo "❌ PostgreSQL is not running. Please start PostgreSQL first."
    exit 1
fi

# Set password for psql
export PGPASSWORD=$DB_PASSWORD

# Create database
echo "📦 Creating database: $DB_NAME"
psql -U $DB_USER -c "DROP DATABASE IF EXISTS $DB_NAME;" 2>/dev/null
psql -U $DB_USER -c "CREATE DATABASE $DB_NAME;" || {
    echo "❌ Failed to create database. Please check PostgreSQL connection."
    echo "   Trying with createdb command..."
    createdb -U $DB_USER $DB_NAME 2>/dev/null || {
        echo "❌ Failed. Please create database manually:"
        echo "   createdb -U postgres tvproje"
        exit 1
    }
}

echo "✅ Database created"

# Run schema
echo "📋 Running database schema..."
psql -U $DB_USER -d $DB_NAME -f database/schema-local.sql || {
    echo "❌ Failed to run schema"
    exit 1
}

echo "✅ Schema applied"

# Create super admin user (with bcrypt hash)
# Note: We'll use a simple approach - password hash will be generated by backend
echo "👤 Creating super admin user..."
echo "⚠️  Note: Password will be hashed by backend on first login"

# Insert super admin (password will be set via backend API)
# For now, we'll create a placeholder that backend can update
psql -U $DB_USER -d $DB_NAME << EOF
-- Create a temporary password hash (will be updated by backend)
-- Using a simple hash for now - backend should update this
INSERT INTO users (email, password_hash, role, business_id)
VALUES ('$ADMIN_EMAIL', 'temp_hash_will_be_updated', 'super_admin', NULL)
ON CONFLICT (email) DO UPDATE SET role = 'super_admin';
EOF

echo "✅ Super admin user created: $ADMIN_EMAIL"
echo ""
echo "📝 Next: Update backend/.env with local PostgreSQL connection"
echo "   Then start backend to set the password hash"
